DROP TABLE IF EXISTS Tarefas;
DROP TABLE IF EXISTS Usuarios;

CREATE TABLE IF NOT EXISTS Tarefas(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    id_usuario INTEGER NOT NULL,
    titulo TEXT NOT NULL,
    descricao TEXT,
    criada_em DATE DEFAULT CURRENT_TIMESTAMP,
    concluido_em TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Usuarios(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL UNIQUE,
    hash_senha TEXT NOT NULL
);
